### ISSUE TITLE
群晖docker部署的trilium能使用这个中文吗？

### ISSUE THREAD

**Issue by yunzhongci** [Nriver/trilium-translation#2]
群晖docker部署的trilium能使用这个中文吗？
怎么使用？

**Comment by Nriver** [comment]
我在docker hub上建了一个镜像, 可以直接用[docker-compose.yml](https://github.com/Nriver/trilium-translation/blob/main/docker-compose.yml)文件运行.
我没有用过群晖, 你可以参考那个yml文件, 用nriver/trilium-cn这个镜像, 挂载/root/trilium-data目录来存数据, 映射8080端口应该就能用了.

**Comment by yunzhongci** [comment]
> 建了一个镜像的docker hub，可以直接运行[docker-compose.yml](https://github.com/Nriver/trilium-translation/blob/main/docker-compose.yml)文件。
> 我没有用过群晖，可以参考那个yml文件，使用nriver/trilium-cn镜像，挂载/root/trilium-data目录存储数据，映射端口8080应该可以使用。

非常感谢，已经按照你的方式运营成功，谢谢

**Comment by kaka77** [comment]
> > 建了一个镜像的docker hub，可以直接运行[docker-compose.yml](https://github.com/Nriver/trilium-translation/blob/main/docker-compose.yml)文件。
> > 我没有用过群晖，可以参考那个yml文件，使用nriver/trilium-cn镜像，挂载/root/trilium-data目录存储数据，映射端口8080应该可以使用。
> 
> 非常感谢，已经按照你的方式运营成功，谢谢

您好，能否分享下配置么？我也是群晖，但是按照配置出错了，目录也建了，目前不知道什么问题。。。


`Error: ENOENT: no such file or directory, mkdir '/volume1/docker/trilium-data'
    at Object.mkdirSync (node:fs:1398:3)
    at getTriliumDataDir (/app/src/services/data_dir.js:41:16)
    at Object.<anonymous> (/app/src/services/data_dir.js:62:26)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/app/src/services/session_secret.js:5:17) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/volume1/docker/trilium-data'
}

Node.js v18.18.2
`
