### ISSUE TITLE
请问下这个是哪里出错了呢?

### ISSUE THREAD

**Issue by JustinWuCN** [Nriver/trilium-translation#5]
部署到了服务器上,
在写笔记的过程中,会卡住.
查看LOG文件,报如下错误.

```
17:17:16.290 JS Error: 未捕获的错误: 信息: Uncaught CKEditorError: Cannot read properties of null (reading '_source')
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-Cannot read properties of null (reading '_source'), URL: http://dormanter.duckdns.org:8081/#root/7EYObexys1Pm/fSiuGE1j7pyy-Nl8B, 行数: 5, 列数: 5908, 错误对象: {"name":"CKEditorError","context":{}}, 堆栈: TypeError: Cannot read properties of null (reading '_source')
    at new Es (<anonymous>:5:242091)
    at Ls (<anonymous>:5:249180)
    at Fs (<anonymous>:5:248681)
    at Gs.scrollToTheSelection (<anonymous>:5:252796)
    at Object.listenTo.priority (<anonymous>:5:535459)
    at Object.fire (<anonymous>:5:123360)
    at kn (<anonymous>:5:189271)
    at yn.fire (<anonymous>:5:188775)
    at o (<anonymous>:5:534089)
    at Object.<anonymous> (<anonymous>:5:534465)^M
Stack: Error
    at Object.v [as logError] (http://dormanter.duckdns.org:8081/app-dist/desktop.js:2:86771)
    at Ie.window.onerror (http://dormanter.duckdns.org:8081/app-dist/desktop.js:2:347915)
17:17:16.475 JS Error: 未捕获的错误: 信息: Uncaught CKEditorError: Cannot read properties of null (reading '_source')
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-Cannot read properties of null (reading '_source'), URL: http://dormanter.duckdns.org:8081/#root/7EYObexys1Pm/fSiuGE1j7pyy-Nl8B, 行数: 5, 列数: 5908, 错误对象: {"name":"CKEditorError","context":{}}, 堆栈: TypeError: Cannot read properties of null (reading '_source')
    at new Es (<anonymous>:5:242091)
    at Ls (<anonymous>:5:249180)
    at Fs (<anonymous>:5:248681)
    at Gs.scrollToTheSelection (<anonymous>:5:252796)
    at Object.listenTo.priority (<anonymous>:5:535459)
    at Object.fire (<anonymous>:5:123360)
    at kn (<anonymous>:5:189271)
    at yn.fire (<anonymous>:5:188775)
    at o (<anonymous>:5:534089)
    at Object.<anonymous> (<anonymous>:5:534465)^M
Stack: Error
    at Object.v [as logError] (http://dormanter.duckdns.org:8081/app-dist/desktop.js:2:86771)
    at Ie.window.onerror (http://dormanter.duckdns.org:8081/app-dist/desktop.js:2:347915)
17:17:16.793 JS Error: 未捕获的错误: 信息: Uncaught CKEditorError: Cannot read properties of null (reading '_source')
```

**Comment by Nriver** [comment]
我在网络环境不稳定的时候遇到过整个页面卡住的情况，刷新一下又好了，不过我没有留意过报错信息。
建议你去trilium的作者那里问一下哦：
https://github.com/zadam/trilium/issues
